### ISSUE TITLE
Submit Query button shouldn't be disabled after selecting a bbox

### ISSUE THREAD

**Issue by philvarner** [sat-utils/sat-api-browser#23]
Existing behavior:

Current behavior for me is that 
1) Search Query button is disabled.
2) Select Bbox. SQ button is still disabled (I feel it should be enabled at this time).
3) Add a Property Filter (e.g., cloud_cover)
4) Modify the value of that Property Filter, even if the default is a valid value (e.g., 50)
5) Search Query button is now enabled.

Desired behavior:
Submit Query button shouldn't be disabled after selecting a bbox

**Comment by sharkinsspatial** [comment]
@philvarner I agree 👍One should be able submit a search without any filters applied.  I will try to issue a PR for this later this week.
