### ISSUE TITLE
Failed prop type: The prop `resultsTotal` is marked as required in `ResultsPaging`, but its value is `undefined`.

### ISSUE THREAD

**Issue by philvarner** [sat-utils/sat-api-browser#28]
```
Warning: Failed prop type: The prop `resultsTotal` is marked as required in `ResultsPaging`, but its value is `undefined`.
```

result from query is: https://gist.github.com/philvarner/90721d77d7c41f598f3687e2345be962

**Comment by sharkinsspatial** [comment]
@philvarner Do you have an open API endpoint I could do integration testing against for this issue?  For the short term I will include a fix for APIs that don't return search metadata.  Are you planning on implementing https://github.com/radiantearth/stac-spec/pull/482/files?  I will update the results parsing to use this once we bring the `sat-api` up to spec.

**Comment by philvarner** [comment]
https://stac.astraea.earth/api/v2/stac/search
